[package]
name = "rlogs"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "logs for rbitcoin"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
ansi_term = "0.12.1"
log = "0.4.0"
env_logger = "0.8.4"

